//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace BungieNet.Destiny
{
	/// <summary>
	/// If the plug has a specific custom style, this enumeration will represent that style/those styles.
	/// </summary>
	[Flags]
	public enum PlugUiStyles
	{
		None = 0x0,

		Masterwork = 0x1
	}
}
